### ISSUE TITLE
Tooltips for style buttons

### ISSUE THREAD

**Issue by Cito** [sn-extensions/bold-editor#3]
Maybe the tooltips for the two buttons "Format" and "Style" should be "Paragraph style" and "Character style" instead - thats clearer. At first I didn't understand that "Style" was only for character styles. I also overlooked the "Format" button because Word uses that symbol to show/hide whitespace. Maybe consider using different symbols as well.

**Comment by mobitar** [comment]
This is out-of-box vendor behavior. Although styles really apply to words, not characters. But typically these sort of language things are resolved for users once they use the editor for a day or two, and enter into the relative language used in the world of this editor.

**Comment by Cito** [comment]
Yes, it's not really important, just makes the onboarding a bit easier. Most important is having paragraph styles in the first place. Much easier to say "this is code" or "this is a heading" than setting font styles and sizes every time. And automatically have consistent styles everywhere. I really don't understand why so many popular tools like Evernote don't offer paragraph styles.
